% function Hd = df_lp;
clear
clc
%DF_LP Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 24-Aug-2015 15:43:54

Fpass = 500;   % Passband Frequency
Fstop = 700;   % Stopband Frequency
Apass = 3;     % Passband Ripple (dB)
Astop = 40;    % Stopband Attenuation (dB)
Fs    = 2500;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'cheby2', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);

[num,den]=sos_C_header_show(Hd)

