function [fitresult, gof] = createFit_HertzModel(z_piezo, force)
%CREATEFIT(Z_PIEZO,FORCE)
%  Create a fit.
%
%  Data for 'Hertz model' fit:
%      X Input : z_piezo
%      Y Output: force
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-May-2015 18:43:16


%% Fit: 'Hertz model'.
[xData, yData] = prepareCurveData( z_piezo, force );

% Set up fittype and options.
ft = fittype( 'K*(x+a)^1.5+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.138624442828679 0.149294005559057 0.257508254123736];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure%( 100);
h = plot( fitresult, xData, yData ,'.-');
legend( h, 'force vs. indent depth', 'Hertz model', 'Location', 'NorthEast' );
% Label axes
xlabel( 'indent depth (nm)' );
ylabel( 'force (nN)' );
grid on


